### ISSUE TITLE
is there an inbuilt pysindy package for identifying sparse models of dynamic systems having rational functions? 

### ISSUE THREAD

**Issue by divgup** [dynamicslab/pysindy#101]

**Comment by kpchamp** [comment]
I don't believe this has been built into the package yet, but you may want to check out [this paper](https://arxiv.org/abs/2004.02322) and [associated code package](https://github.com/dynamicslab/SINDy-PI) which has more information on using SINDy for rational functions.

**Comment by divgup** [comment]
Thanks for your reply. I have read the paper and Sindy-PI implementation in MATLAB. I wanted an implementation in python, but I didn't find any. So now I'm thinking of implementing some functions in python for identifying rational functions.

**Comment by briandesilva** [comment]
The creator of SINDy-PI, Kadierdan, previously expressed interest in contributing a SINDy-PI implementation to PySINDy a few months ago, but I'm not sure if he's still planning on doing so.

**Comment by akaptano** [comment]
Some progress on this... I have started a new sindy-pi branch that has a rough version of SINDy-PI implemented. The main issue is that the "full, constrained version" of SINDy-PI is implemented (Equation 3.7 in Kadierdan's paper), which scales poorly with the size of the SINDy library since Xi is of size p x p, and p (the size of the SINDy library) already scales combinatorically in the number of input features. So even at 4D models I am beginning to see out-of-memory errors. The solution is to parallelize this process, and then reduce at the end to a single set of coefficients that is the best fit. I want to discuss with @briandesilva about what would be the best option for this; we may also want to discuss with Kadierdan.

**Comment by akaptano** [comment]
SINDy-PI is implemented under the sindypi branch of this github repo, hopefully to be integrated into the main branch shortly. In 9_sindypi_examples.ipynb you can find a simple use case. I found that more difficult cases require multiple_trajectories=True, with lots and lots of training data, for convergence, so be warned. The documentation should also improve in the next few weeks, but reach out if you are having serious trouble using the method.

**Comment by alka8765** [comment]
> SINDy-PI is implemented under the sindypi branch of this github repo, hopefully to be integrated into the main branch shortly. In 9_sindypi_examples.ipynb you can find a simple use case. I found that more difficult cases require multiple_trajectories=True, with lots and lots of training data, for convergence, so be warned. The documentation should also improve in the next few weeks, but reach out if you are having serious trouble using the method.

Hii, Can you let me know is there any example that uses SINDy PI in Python for more then one state variables? I am unable to figure out that how the output will be in this case as a sequence of models being produced here.
