### ISSUE TITLE
constrain on states

### ISSUE THREAD

**Issue by bathukorallage** [dynamicslab/pysindy#104]
## Is your feature request related to a problem? Please describe.

Hello,
I have started to learn pysindy and am going over the examples now.
One question that I have is, is it possible to impose a constrain on the states?
As an example, I would like to get a SIR - model from a data, but in general this model has a constraint: S+ I + R = 1.

Thank you

**Comment by akaptano** [comment]
Yes this is doable. There are constrained SINDy versions available in the optimizers folder for affine constraints. Since your example constraint is equivalent to dS/dt + dI/dt + dR/dt = 0, and SINDy is fitting d/dt[S, I, R] = Theta(...) * Xi, this can be cast as a constraint on the coefficients in Xi -- i.e. that Xi^S + Xi^I + Xi^R = 0 since the Theta matrix is the same for each. This can be put into the affine form C*Xi = d = 0, which you will have to work out. Let me know if you have any more questions.

**Comment by buathukorala** [comment]
Thank you for the suggestion Alan, it is very useful. I will check the implemented optimizers and the related examples.

**Comment by slimaneaymen** [comment]
Hello @akaptano,
I wonder if there is a way to specify which interaction to be done between the terms, in other words how to constrain the theta matrix. For ex: if i have x,y,z , I would like to constrain theta to have only the individual terms (x, y, z) + the interaction: xz.

**Comment by akaptano** [comment]
Hi @slimaneaymen 

The answer is yes, but your example can be done in two ways in the code. The first way is to constrain the model coefficient Xi, rather than constraining theta. This is what I described above, and it can be done in a way that the model only produces (x, y, z) terms + an interaction xz term. 

The other way is to design a theta matrix that only contains the interaction term xz. This can be done with the GeneralizedLibrary class since this allows you to specify only a subset of the inputs for library generation -- check out the example at the bottom of the Example 1 Jupyter notebook to see how this can be done, or the last of the recent Youtube lectures that I put online.

Best,
Alan
