### ISSUE TITLE
[BUG]: mismatched in model.print()  and model.coefficients()

### ISSUE THREAD

**Issue by buathukorala** [dynamicslab/pysindy#113]
![sindy_op](https://user-images.githubusercontent.com/10818478/121365925-ad51ce00-c8fe-11eb-875b-688017ce82f8.PNG)

Dear PiSINDy developers, 

I have used a data set with 116-dimensions to get a system of ODEs using sindy algorithm. 
When I inspect the equations and coefficients using model.print() and model.coefficients(), I see a constant term (-0.004) in Eq1, however, I do not see the same constant term in the  corresponding coefficient array (please see the attached image). 

I see the same issue in all the remaining equations.

Do you have any comments or suggestions about this?

Thank you in advance!

Bhagya  
  
 

### PySINDy/Python version information:

 1.3.0

**Comment by akaptano** [comment]
First of all, wow a 116D model! Nice. Can you try model.print(precision=6)? And can you also print what you are doing for 1) your SINDy library (are you using a custom library or the pre-made polynomial one?) and 2) how you are obtaining coeff, which presumably you set coeff = model.coefficients()? 

My guess is that somehow the ordering in your library is different than what you think it is.

Best,
Alan

**Comment by buathukorala** [comment]
Hi Alan,
Thanks for the prompt reply. I am using fMRI time series data set with 116D.
I just tried with precision=6. 

(1). I use the pre-made polynomial library with degree =1.  
(2). To get the coefficients, I use  `coeff = model.coefficients()`

and to get the the coefficients that correspond to equation 1, I use  ` coeff[0,:]`.

When I compare the coefficients of  `x0'` with the array ` coeff[0,:]` everything matches, except the last term in the equation. I do not see it in the ` coeff[0,:]`. 
Please see the image below. Thanks again !
 
![names](https://user-images.githubusercontent.com/10818478/121390184-bea4d580-c912-11eb-9b1e-6c3df29c4833.PNG)
![sindy_op2](https://user-images.githubusercontent.com/10818478/121390220-c5cbe380-c912-11eb-8252-86b77d31f862.PNG)

**Comment by akaptano** [comment]
Great, thanks for the info. I'll try this on a simple 3D example in an hour or so and try to reproduce this error.

**Comment by buathukorala** [comment]
Thank you! I am attaching both Jupiter note book and tsv file, if you want to use.

[sindy files.zip](https://github.com/dynamicslab/pysindy/files/6625460/sindy.files.zip)

**Comment by akaptano** [comment]
This appears to be a genuine bug. I can reproduce this with sklearn's Lasso or ElasticNet optimizers, but ps.STLSQ works correctly. Note that in this case the constant coefficient term in model.print() looks like:
x0' = 0.398 1 + -0.098 x0 + 1.987 x1
Instead of:
x0' = -0.098 x0 + 1.987 x1 + 0.398

Using opt = ElasticNet(alpha=0.1) and then printing opt.coef_ is also omitting the constant coefficients. Curiously, the constant coefficients appear to only be saved in opt.intercept_. @briandesilva this should be a straightforward fix: when the optimizer is from sklearn, after fitting just set opt.coef_[:, 0] = opt.intercept_.

Bhagya, you should be able to just directly use opt.coef_[:, 0] = opt.intercept_ to fix your model coefficients for now, but we will make a bug fix soon so that this behavior is automatic for sklearn optimizers.

Best,
Alan

**Comment by buathukorala** [comment]
Great! Thanks Alan.
This make sense now.

Thanks again for working and fixing this issue.
