### ISSUE TITLE
[Question] Is it possible to use other formulations?

### ISSUE THREAD

**Issue by A3EKV** [dynamicslab/pysindy#126]
Hello,
I have a very basic/none understanding of what is going on control or some applications of this package. However, I have tested it with some examples but I don't get the expected results, because I have some questions:

* Is it possible to use PySINDY to solve systems of the type (Second Order ODE): 
```
x''(t) = f(x(t))
```
?
* Is it possible to use PySINDY for system where the governing equations are of the form:
```
x' = g(f(x(t)))
```
Where a `g` is a function that the user can specify (e.g `sin`, `cos`, `exp`, etc.)?

Thank you very much

**Comment by akaptano** [comment]
Yes and yes. For the second order ODE, all you need to do is pass your own x'' data to model.fit like so:
model.fit(x=x_train, x_dot=x_ddot_train, t=dt)
This requires you to calculate the second derivative separately, and then pass it to the model, since the default, model.fit(x=x_train, t=dt), generates the first derivative. Let me know if you need help with that. 

For the second question, I assume you mean g(x(t)) instead of g(f(x(t)) since you have not specified what kind of functions are in f. The Sin and Cos functions are implemented in FourierLibrary. If you need more specialized functions, or a mix of functions, please see the CustomLibrary functionality in the Example 1 Jupyter notebook. Let me know if anything is unclear.

**Comment by A3EKV** [comment]
@akaptano 
Thank you very much for your reply.

> `model.fit(x=x_train, x_dot=x_ddot_train, t=dt)`
I can't see how this can be used to find ODEs of second order? because the Left hand side (lhs) in the output will be always the first order derivative. If I am not mistaken that syntax is used when I would like to specify the derivative myself without relying on pySINDy to compute it.

* For the second question I mean `x'(t) = g(f(x(t)))` not `x'(t) = f(x(t))` (because that's the default behaviour).

Thank you

**Comment by akaptano** [comment]
Good questions. 
1) You are correct that the lhs of x_dot=x_ddot_train is always called "x_dot" but this is just a placeholder for whatever you want to put on the lhs of the SINDy equation. In other words, if you pass **any** matrix that has the correct size, it will use this for the lhs of the SINDy equation. The only thing that will be incorrect is if you try to use model.simulate (i.e. scipy odeint/solve_ivp), which assumes a first-order system of equations. The assumption is first-order because any higher-order system of ODEs can always be reduced to a system of first order ODEs. 

2) Assuming g and f are two different function libraries, I would recommend handling this case with the CustomLibrary functionality I mentioned. Note that lambdas can be nested:
        library1_functions = [
            lambda x : np.exp(x),
            lambda x : 1./x,
            lambda x : x,
            lambda x : np.sin(2 * x)
        ]
        library2_functions = [
            lambda x : x ** 2
        ]
        for i in range(4):
            print(library1_functions[i](library2_functions[0](2)))

 produces 54.598150033144236, 0.25, 4, 0.9893582466233818. 
 However, the functionality to put in nested lambdas as a feature library is not currently available. For now, you have to hardcode it instead:
 library_functions = [
            lambda x : np.exp(x ** 2),
            lambda x : 1./x ** 2,
            lambda x : x ** 2,
            lambda x : np.sin(2 * x ** 2)
        ]
Depending on future interest, we might consider implementing this feature. You are welcome to implement it as well.
