### ISSUE TITLE
Allowing x and x_dot to be tuples

### ISSUE THREAD

**Issue by A3EKV** [dynamicslab/pysindy#127]
## Is your feature request related to a problem? Please describe.

```
import pysindy as ps
...
X = np.stack((x,y,z),axis=1)
XDOT = np.stack((xdot,ydot,zdot), axis=1)
model = ps.SINDy()
model.fit(x=X, x_xdot=XDOT)
```
The fit function requires the data to be passed in as a stack of arrays. I can't see why is this enforced and not allowing tuples? Allowing tuples will make it very flexible

```
# without manullay stacking data
model.fit(x=(x,y,z), x_dot=(xdot,ydot,zdot))
```
I can't see any reason why this task is delegated to the user not the function itself. The function needs to check if the argument is  a tuple then convert it to a stacked array.

Thank you

**Comment by Jacob-Stevens-Haas** [comment]
> I can't see any reason why this task is delegated to the user not the function itself.

Because allowing more general input conventions doesn't add any real functionality and makes the API more complex.  In general, type checking is usually implemented to support backwards compatability, not to expand functionality.

This suggestion is a great case in point: allowing tuples as another way of specifying coordinates would have made a recent refactor more complex.  Passing sequences of arrays is reserved for multiple trajectories of the same coordinates.
