### ISSUE TITLE
[Deps] CMake is needed.

### ISSUE THREAD

**Issue by loiseaujc** [dynamicslab/pysindy#150]
Hej,

Some of my students have started to use pysindy for my dynamical system class and encounter an issue while installing the code from pip. CMake is needed to compile one of the deps.

At least, we should mention this in the README. Ideally, it should be explicitly added as a dependency in the pip stuff but I have no idea how to do so.

++

**Comment by akaptano** [comment]
Hey JC, good to hear. Any idea which dependency needs cmake? Could you post the error messages that students are seeing? I have not heard of this issue before so I want to make sure what the issue is before I add it as a dependency. 

Also, I highly recommend that you have your students download the latest release (1.6.1 https://pypi.org/project/pysindy/).

**Comment by akaptano** [comment]
@loiseaujc any update on this? How goes your new class?

**Comment by dajoedic** [comment]
Hi @akaptano 
Same "issue" here: The package that needs CMake is qdldl.

**Comment by akaptano** [comment]
@briandesilva Any idea about this? qdldl is not in the requirements.txt file, but it is installed on my computers, so my guess is that qdldl gets installed when you install some of the other requirements. Why is isn't being installed automatically on Windows machines is not clear. Maybe adding cmake as a dependency is the easiest solution.

**Comment by briandesilva** [comment]
It looks like this may be an issue with qdldl. Apparently other Windows 10 users are having trouble installing it properly (see [this](https://github.com/osqp/qdldl-python/issues/19) issue). A possible solution, suggested [here](https://github.com/cvxpy/cvxpy/issues/1625), is to require `cvxpy-base` instead of `cvxpy`. Though I'm not sure whether cvxpy-base has all the functionality we need.

**Comment by akaptano** [comment]
I found a similar cmake issue on my desktop Mac computer, so I added it to the requirements.
