### ISSUE TITLE
Extrapolating 1D PDE with discovered PDE and constraint of known timepoints

### ISSUE THREAD

**Issue by Imraj-Singh** [dynamicslab/pysindy#168]
I am having some trouble getting my model to work and would appreciate being pointed in the right direction.

I have data from a scalar spatiotemporal field with 100 spatial grid points and 50 temporal grid points, i.e. in the form (Nx, Nt, 1). 

This scalar spatiotemporal field "u" is over the "x" and "t" spatial and temporal domains. It is known that the PDE is periodic in time with the iterate from the 50th timepoint arriving back at timepoint 1 smoothly. Additionally, there is uniform spatial sampling and temporal sampling in the training data.

With that in mind I set up the problem with:

```
pde_lib = ps.PDELibrary(
    library_functions=library_functions,
    function_names=library_function_names,
    derivative_order=2,
    spatial_grid=x.T,
    include_bias=True,
    is_uniform=True,
    periodic=True
)
print('STLSQ model: ')
optimizer = ps.STLSQ(threshold=0.01, alpha=1e-5, 
                     normalize_columns=True)
model = ps.SINDy(feature_library=pde_lib, optimizer=optimizer)
model.fit(u_train, x_dot=u_dot_train)
```
I am attempting to get `model.simulate` working on for example the first timepoint, with constraints of all other time points, and a finer temporal discretisation. Is this possible? In essence, is there a way of extrapolating to new timepoints with the discovered PDE as well as known timepoints as contraints?

Thanks,
Imraj

**Comment by akaptano** [comment]
Hi Imraj,

From what I gather, you want to simulate the PDE model that is identified, but to do so in such a way that enforces the periodicity in time. This is not generally possible -- what you need to do is only put terms in your candidate function library that obey this symmetry. 

There is a second issue -- model.simulate is intended for use evolving systems of ODEs (it interfaces with odeint and solve_ivp). Simulating PDEs in time in general requires more sophisticated methods, so I recommend doing this with your own code. Otherwise model.simulate will be very confused by the spatial derivative terms in your model. Happy to discuss this more.

Best,
Alan

**Comment by Imraj-Singh** [comment]
Hi Alan,

Thank you for your quick response!

How would you suggest you create a candidate function that obeys that symmetry? Can you include time in the candidate functions? Also, what is "periodic=True" specifying in ps.PDELibrary, is that the periodicity of the spatial derivative?

That makes sense. I guess it depends on the identified PDE, but are you aware of libraries that are able to simulate PDEs?

Kind regards,
Imraj
