### ISSUE TITLE
Using model.simulate() on a self defined system of ODEs

### ISSUE THREAD

**Issue by shekhar477** [dynamicslab/pysindy#188]
Can the numerical integration be performed using model.simulate() on a self-defined system of ODEs rather than the system of ODEs which PySINDy generates?

**Comment by akaptano** [comment]
I do not believe so. But model.simulate() is just a front-end that uses scipy.solve_ivp (or scipy.odeint) which you can use for your self-defined system of ODEs, no problem.

**Comment by shekhar477** [comment]
I’m a bit skeptical about how to use the solve ivp for a system of ODEs for which the control variable is in the array format and not the function?
For instance, let’s say we have 2 state variable and 2 control variable system:
(x0)’ = 2*x0 - 4*x1 + u0 - 0.5*u1
(x1)’ = -0.5*x0 - 2*x1 + 3* u1

How would we integrate it?

**Comment by akaptano** [comment]
solve_ivp and other ODE integrators allow for functions that specify a ODE as you have above. In this case the function is my_ode(t, x, u) and you can specify u as a time series:
my_ode(t, x, u, original_time_series):
    ... find index in original_time_series that is closest to t ...
    ... compute x0 = 2 x0  - 4 x1 + u0[index] - 0.5 u1[index] ...
or something to this effect. You can do some fancier things to interpolate u instead of choosing the nearest value to the  current integration timstep
