### ISSUE TITLE
Multiple subjects and Missing data

### ISSUE THREAD

**Issue by jerul** [dynamicslab/pysindy#200]
Hi!

Thanks for this wonderful package.
I am interested in using this method in medical data, which generally has two issues:
- short time-series of many individuals (e.g., N=500 with each 5-10 values over time for the variables)
- many missings (sometimes only 2-3 values over time available for a given variable). In fact, there may not be any time points available that have every variable for a given individual.
 
Perhaps I've missed it in the documentation but it's unclear to me how to work with (1) multiple individuals and (2) NaNs. In general, this should not be a problem as the cost function could simply sum over the multiple individuals and omit the missing values.

I'm wondering if there's a way to make this work with pysindy?

Lastly: I was also wondering if there is a way to restrict the parameter search space, e.g., to only positive values for the parameters?

Thanks!

**Comment by akaptano** [comment]
If "the individuals" are your variables (i.e. you are fitting a model for each one) you will need at least a few time points available for each individual. This is because SINDy fits each variable separately and point wise. If you merely want to fit a model to *all* the individuals (in other words, you want one model, from the data of all individuals), you can simply concatenate all the time series, eliminate the NaNs, and pass this time series data as a single variable. Please clarify if you were thinking of something else.

Restricting the parameter search space is done with the "ConstrainedSR3" optimizer, see the example 1 Jupyter notebook for simple usage. You can easily build in constraints that require all the coefficients to be positive.

Best,
Alan

**Comment by akaptano** [comment]
I'm still not totally sure what you want to do since you say "use all the timesteps of all individuals to obtain a single set of model parameters" but then later "how does SINDy know that it's dealing with multiple individuals?" 

What is important is that you have, say, 6 variables (BMI, blood pressure, etc.) and each of these variables is a time series (with some NaNs) for each individual.  So you want to fit a SINDy model for a set of data that is a matrix of size 6 x num_time_points.

You can also treat each individual as a separate instantiation of the model system you want to build -- this is like using the "multiple_trajectories" flag (see the example 1 jupyter notebook for a quick example). You can additionally just concatenate all the time series for all the individuals together, such that your total data is now a matrix of size 6 x num_time_points * num_individuals. SINDy can't tell the difference either way. 

You are right that the NaNs at different time points will be an issue here. I recommend some simple interpolation. For instance, my expectation is that most people with a certain BMI at 6 months and at 18 months should have a similar BMI at 12 months. BMI, blood pressure, etc. should be fairly "well-behaved" variables that you can roughly interpolate. If you add some figures from the data here, I can provide additional advice.

Best,
Alan
