### ISSUE TITLE
New Related Package

### ISSUE THREAD

**Issue by matteoettam09** [dynamicslab/pysindy#249]
## Describe the solution you'd like

Dear all, would it be possible to add this line to the README of this repository?

* `SymINDy <https://github.com/andreikitaitsev/SymINDy>`_ - Symbolic Identification of Nonlinear Dynamics: a genetic-programming-based generalization of SINDy combining Sparse and Symbolic Regression.

Thank you very much,
Matteo

**Comment by Jacob-Stevens-Haas** [comment]
Hi Matteo, we're very excited about people extending the SINDy work.  I read the JOSS submission and through some of the code.  @akaptano, how do we want to manage 3rd party repos with different flavors of SINDy? My only concern here is naming, given that Example 9 is SINDy with symbolic regression in a different way.

**Comment by matteoettam09** [comment]
Sorry, I am not sure I understand. Are you referencing a SINDy example performing symbolic regression? If so, could you share? I couldn't find any Example 0 in the documentation.

**Comment by Jacob-Stevens-Haas** [comment]
https://github.com/dynamicslab/pysindy/blob/master/examples/9_sindypi_with_sympy.ipynb deals with implicit differential equations.  Since ODE solvers can't solve these equations, it requires the `sympy` package for symbolic regression.  It's not really my area of knowledge, though.

This issue also provides an opportunity for the maintainer/researcher community to consider several related questions, so I've opened a discussion.  To clarify, none of these questions really need to be answered for this issue, and I'd be happy approve a PR to add your link to the README.

**Comment by matteoettam09** [comment]
Thanks! I understand that the line between valuable projects building on SINDy and parasites of your repo is not so clear.

I created a pull request:

- https://github.com/dynamicslab/pysindy/pull/251

but I understand if in the future you change your mind and decide to remove some/all related packages.

All the best
