### ISSUE TITLE
Setting up transport equations example request

### ISSUE THREAD

**Issue by victor-armegioiu** [dynamicslab/pysindy#265]
Hi everyone,

## Is your feature request related to a problem? Please describe.
I've gone through the video tutorial and documentation and tried for some time on my own,
but I haven't been able to properly set up a PDE library for transport equations.
I'm also a bit confused about the right choice of the underlying library (i.e. general, tensor etc.).

## Describe the solution you'd like
I'd tremendously appreciate a simple working example (as a notebook or something of the sort) for setting up a transport equation like:

$u_t - y \cdot u_x + x \cdot u_y = 0$, depending on some smooth initial data $u_0(x, y) := u(0, x, y)$ for all $(x, y) \in \mathbb{R}^2$ 

## Additional context
These equations are particularly important for my work (and other people working with symmetries) since they provide a particularly easy way of generating PDEs that satisfy some symmetry, i.e. in this case the vector field $(-y, x)$ corresponds to the infinitesimal generator of $SO(2)$, so generating functions $u$ that respect this symmetry simply amounts to applying the corresponding infinitesimal generator (or composition thereof) to a function and setting the resulting PDE to 0.  Naturally, this is a toy example, but we are considering more complicated symmetries so having a working example would be of tremendous help.

Thanks a lot for taking the time to read this!

**Comment by akaptano** [comment]
Hi Victor,

A few notes on this:
1. Your PDE depends on the spatial coordinates, so you will need the GeneralizedLibrary functionality (see the end of the example 1 Jupyter notebook in examples/). You also want terms that combine spatial coordinates and terms depending on the solution variable u, so you need the TensorLibrary functionality. So for your transport equation, you would set up a linear polynomial library in the (x, y) coordinates and a PDElibrary with 1st-order derivatives for the (u) variable, and tensor them together to get terms like you quoted above. 
2. SINDy performance will be independent of your smooth initial data since it is only fitting the time evolution of u. 
3. If you get this working for more generic symmetries, it would be a great addition to the code. We don't currently have any pre-defined libraries that only build terms obeying some symmetry like translation invariance. 

If you could send some data over, I will be happy to write up the code to get you going here, but I don't want to have to do the work to generate the example myself, i.e. picking some initial condition, solving this with the Fourier transform, etc.
