### ISSUE TITLE
How to Fit 2D PDE with AMR using SINDY

### ISSUE THREAD

**Issue by cdelv** [dynamicslab/pysindy#277]
Hi, I have data generated with a simulation. The data is 2D in space and is time-dependent. For each time step I have a .csv file with the following information: (t,x,y,z,u). I want to find the governing equation of u(t,x,y). The main problem I'm having is that the simulation that generated the data used AMR, therefore the coordinates where u and the number of points evaluated change every time step. Then, I don't know how to format the data for the fitting. 

I'll leave here a couple of time steps if someone wants to help me figure out how to load the data and fit it. Here is some code that loads the data with pandas
```
import pandas as pd
data = pd.read_csv("a_0.csv")
data = data[data['Points:1'] >= 0]  #due to the simetry of the data
data = data.rename(columns = {"Time":"t", "Points:0":"x", "Points:1":"y", "Points:2":"z","W_mag:"u"})
data = data[["t", "x", "y", "z", "u"]]
```
This is just for convenience. If you want to see the data just do
```
import matplotlib.pyplot as plt
plt.tricontour(data["x"],data["y"],data["u"], levels=45, cmap="coolwarm")
```

The code I tried to use is basically the one in this video: https://www.youtube.com/watch?v=PMX-4IIUEKE&list=PLN90bHJU-JLoOfEk0KyBs2qLTV7OkMZ25&index=9. 

I really would appreciate it if someone can help me with this. I'm new to SINDY and have been stuck with this the whole week. 

Here is the data:
[a_0.csv](https://github.com/dynamicslab/pysindy/files/10419118/a_0.csv)
[a_1.csv](https://github.com/dynamicslab/pysindy/files/10419119/a_1.csv)
[a_2.csv](https://github.com/dynamicslab/pysindy/files/10419120/a_2.csv)

Best regards.

**Comment by akaptano** [comment]
Hi there! I think that data from AMR (automatic mesh refinement, I'm assuming) should not _in principle_ be an issue, since the PDE du/dt = ... holds pointwise in the data, and the SINDy data fit is point wise (L2 norm between the data and the model fit). The issue is that our PDE implementation in the code assumes that you have a constant spatiotemporal grid. 

To fit this data, you fill need to go into the PDELibrary code and make some adjustments. For instance, presumably your PDE depends on du/dt, but it is not clear how you would like to compute this. At each timestep, u is evaluated at different spatial locations, so computing du/dt with finite differences (as is the default in PySINDy) doesn't make a lot of sense, since we are now observing u(x, y, z, t) at a different set of locations. 

You will either need to make a number of these choices and adjustments in the internal parts of the code, or you can take your AMR data and interpolate everything onto a single spatiotemporal grid (which can be non-uniform, use the uniform=False flag in the PDELibrary) and use the normal PDELibrary. Let me know if you have any more questions.

Best,
Alan
