### ISSUE TITLE
SINDyCP parameterized library issue

### ISSUE THREAD

**Issue by UtsavAwasthi** [dynamicslab/pysindy#282]
@znicolaou 
When I tried to run the example of parameterized pattern formation, I encountered Attribute Error, when passing the parameters and feature to the ps.ParameterizedLibrary.

**Comment by znicolaou** [comment]
Hi @UtsavAwasthi,

This is almost certainly because of the version of pysindy installed in your environment. We have not yet made an official release with the ParameterizedLibrary to the PyPI server, so if you install with just `pip install pysindy`, you will have a version from this older commit: https://github.com/dynamicslab/pysindy/commit/bc131d9d1deb97febea9c9ad058c77f0e0bb5ddf.

Making a release is on my TODO list, but in the meanwhile you should install directly from a clone of the github repository. I'd recommend the following:

```
git clone https://github.com/dynamicslab/pysindy.git
cd pysindy
pip install -r requirements-dev.txt
```
which will create links of the files in your repository directory to your python environment. Please let me know if you have issues trying it out so we can resolve them before a release!

**Comment by UtsavAwasthi** [comment]
Thank you it worked. I will let you know if I encounter any other issues.
