### ISSUE TITLE
PySINDy upgrade

### ISSUE THREAD

**Issue by DJIDM** [dynamicslab/pysindy#289]
I originally installed PySINDy using conda (pysindy=1.3). I would like to update to the most recent version (pysindy=1.7.3), however this version is currently not available on conda. If I use pip to upgrade, will this cause any issues?

**Comment by znicolaou** [comment]
Hello, @DJIDM,

I'd recommend installing with `pip`, but make sure it's the `pip` for the python environment that you want to use. If you're using conda, for example, do `conda install pip` from the environment you want to modified before `pip install pysindy`, to ensure that the `pip` command modifies your conda environment. Also, you can verify that `which pip` originates from the bin directory of your conda environment rather than some other python environment.
