### ISSUE TITLE
[BUG] The pysindy model coefficients are different from the fitting result directly from STLSQ?

### ISSUE THREAD

**Issue by linguo4** [dynamicslab/pysindy#297]
Hi! For the Lorenz introductory example, I ran the pysindy model first. Then I used the model to calculate the `dx` and constructed library. And I used the STLSQ optimizer to fit the model. The pysindy model coefficients are different from the fitting result directly fit from STLSQ. Is there anything I'm missing? Or how can I reproduce the original SINDy model coefficients here?
![image](https://user-images.githubusercontent.com/67442207/228456026-6f0f05d7-ca54-4631-b7c6-20cc8089ffc1.png)
### Reproducing code example:

```python
import pysindy
import numpy as np
from scipy.integrate import solve_ivp
from pysindy import SINDy
import pysindy as ps
def lorenz(t, z): 
    return [10*(z[1] - z[0]), z[0]*(28 - z[2]) - z[1], z[0]*z[1] - 8/3*z[2]]
t = np.arange(0,200,10.0)
x = solve_ivp(lorenz, (t[0],t[-1]), [-8,8,27], t_eval=t).y.T
optimizer = ps.STLSQ(threshold=0.01)
lib = ps.PolynomialLibrary()
model = SINDy(optimizer = optimizer, feature_library  = lib)
model.fit(x, t=t[1]-t[0])
model.print()
model.coefficients()

li = lib.transform(x)
dx = model.differentiate(x, t=t[1]-t[0])
optimizer.fit(li, dx)
optimizer.coef_
```

**Comment by akaptano** [comment]
In general, the coefficients will be slightly different between the two things you did. We recommend the model = SINDy() approach, which occasionally comes with some pre and post-processing of the data and/or identified model, and makes sure the optimizer has the correct initialization. For instance, above if you set "alpha=0.0" in the STLSQ optimizer it should fix this issue. I think so far that this is a problem of keyword passing but I am hesitant to look into this further because it can be avoided anyways by using the standard model initialization in the code.
