### ISSUE TITLE
control theory for stability?

### ISSUE THREAD

**Issue by ccrnn** [dynamicslab/pysindy#331]
I've been thinking about the problems with numerical stability coming from some pysindy models, and I wondered if you've tried using control theory to design a controller that could iterate slightly on the coefficients until they are stable and simulate? Maybe with MRAC?
I am just learning control theory now & wanted to check if you think this is nonsense or have already tried.
It would be a while before I would have time to try anyway.

**Comment by Jacob-Stevens-Haas** [comment]
My general thought is that you would write this capability _around_ pysindy, as estimators obeying the scikit-learn API (including SINDy) are not re-trainable.

**Comment by akaptano** [comment]
Another point to add here -- if you want to iterate on the coefficients you will typically need to incorporate your scheme as part of the SINDy optimization problem itself. We did this a few years back by incorporating a requirement from a nonlinear stability theorem for this 'Trapping SINDy' method. Otherwise, Jake is right -- you need to wrap it around PySINDy, and keep recomputing SINDy models.

**Comment by ccrnn** [comment]
Thanks for the advice 🙏
I will check out how Trapping SINDy works first, then have a go in a few months when I've learned a bit more.
