### ISSUE TITLE
Data gathered from a simulated system

### ISSUE THREAD

**Issue by maxwell1386** [dynamicslab/pysindy#337]
Hi 
I have simulated a dynamical hybrid  system in matlab 1000 times using 1000 random initial state with 2 variables as output and 4 random inputs for 500 time steps. I have 3 discrete input value and 1 continous input value. Could you tell me how can i model this hybrid dynamical system with pySINDy?

**Comment by Jacob-Stevens-Haas** [comment]
I believe you're looking for control input.  See the `SINDy.fit` documentation - the input values are the argument we call `u`.  Do I understand correctly that your equations look like this?

$\dot x = f(x, y, z_1, z_2, z_3, z_3)\hspace{1in}\dot y = g(x, y, z_1, z_2, z_3, z_3)~~~~~$


FWIW, this is better asked in the discussion tab, rather than as an issue.  We can keep talking about it here, but I'm going to close the issue so it doesn't show as open on github.
