### ISSUE TITLE
Linear Parameter Varying System Identification

### ISSUE THREAD

**Issue by Aditya16828** [dynamicslab/pysindy#346]
**Is it possible to model a Linear Parameter Varying System using this Library??** 
If so then could anyone please provide some hint on how to approach or how to do it??

**Comment by Jacob-Stevens-Haas** [comment]
Possibly.  Can you describe what you mean with equations? (You can use  \$ dollar signs \$ to format equations like LaTeX, e.g. $x^2$)

**Comment by Aditya16828** [comment]
![image](https://github.com/dynamicslab/pysindy/assets/73335791/62c18708-18db-45c5-86a5-775bac8cbdcf)
I am trying to identify this kind of system where **_v_** is a variable, this means that my system matrices will be varying at each data point.

**Comment by Aditya16828** [comment]
Yes it is known.

**Comment by Jacob-Stevens-Haas** [comment]
Then yes, it is possible.  There are three concepts to grasp:
* Control inputs - your $v$ is the `u` parameter in `SINDy.fit()`.  The data needs to conform to `x` (e.g. same number of steps).  These variables get appended to `x` as additional coordinates when passed to the function library.  However, SINDy doesn't try to fit an equation for their dynamics
* Custom functions - There is no library for the $\frac{1}{v}$ or $\frac{1}{v^2}$ functions.  You need to build a [`CustomLibrary`](https://pysindy.readthedocs.io/en/latest/api/pysindy.html#pysindy.CustomLibrary) for the control variable and use a `PolynomialLibrary(degree=1)` for the $x$ variable.
* Multiplying libraries - the [`TensoredLibrary`](https://pysindy.readthedocs.io/en/latest/api/pysindy.html#pysindy.TensoredLibrary) handles multiplying your `CustomLibrary` and `PolynomialLibrary`.  Pay attention to the `inputs_per_library_` parameter, which determines which coordinates of your now-concatenated variable get passed to each library.

**Comment by znicolaou** [comment]
Just to add to @Jacob-Stevens-Haas's solution, the `ParameterizedLibrary` wraps the `TensoredLibrary` with `inputs_per_library_` to simplify this case--check out the first couple of examples in example notebook 17: https://github.com/dynamicslab/pysindy/blob/master/examples/17_parameterized_pattern_formation/parameterized_pattern_formation.ipynb.

**Comment by Jacob-Stevens-Haas** [comment]
@znicolaou I thought ParameterizedLibrary only allowed parametrized coefficients, rather than the $1/v$ and $1/v^2$?  Or is that just when parameterizing Weak terms?

**Comment by znicolaou** [comment]
@Jacob-Stevens-Haas the ParameterizedLibrary broadcasts the input to the same number of (space)-time points as the data, so it's actually fine if the control parameters vary with every point. 

It's not very clear what equation @Aditya16828 is trying to identify--are $x_k$ and $y_k$ 2 by N matrices, where $k=1\ldots N$? Is the second equation supposed to give $y_{k+1}$ on the left hand side rather than $y_k$? Is $u_k$ yet another control parameter, or are $u_k$ and $y_k$ supposed to be the same? 

Anyway, I slightly modified the first logistic map example in notebook 17 to illustrate. Here, there is just `num=1` trajectory, but the logistic parameter $r$ is randomly generated each step as $r_n=3.5+1/v_n$ for a control signal $v_n$ randomly selected between 2 and 3.
```
num = 1
N = 1000
N_drop = 500
r0 = 3.5
vs=2+np.random.random(size=(1,N+N_drop))
xss = []
uss=[]
for v in vs:
    r= r0 + 1/v
    xs = []
    x = 0.5
    for n in range(N + N_drop):
        if n >= N_drop:
            xs = xs + [x]
        x = r[n] * x * (1 - x)
    xss = xss + [np.array(xs)]
    uss=uss+[v[N_drop:]]

feature_lib = ps.PolynomialLibrary(degree=3, include_bias=True)
parameter_lib = ps.CustomLibrary(library_functions=[lambda x:1/x], function_names=[lambda x:x+'^-1'],include_bias=True)
lib = ps.ParameterizedLibrary(
    feature_library=feature_lib,
    parameter_library=parameter_lib,
    num_features=1,
    num_parameters=1,
)
opt = ps.STLSQ(threshold=1e-1, normalize_columns=False)
model = ps.SINDy(
    feature_library=lib, optimizer=opt, feature_names=["x", "v"], discrete_time=True
)
model.fit(xss, u=uss, multiple_trajectories=True)
model.print()
```
The model finds the correct equation:
```
(x)[k+1] = 3.500 1 x[k] + -3.500 1 x[k]^2 + 1.000 v[k]^-1 x[k] + -1.000 v[k]^-1 x[k]^2
```


The only cautionary point is indeed with the `WeakPDELibrary` -- the weak features corresponding to products of spatially inhomogeneous coefficients and library functions will not be correct, since the integration of products does not break into products of integrals.

Hope this helps!

**Comment by Aditya16828** [comment]
Thank u so much for the help; if further doubts occur, I will let u know.

**Comment by Aditya16828** [comment]
Can this same thing be done in state-space form?
