### ISSUE TITLE
Optimizers with linear equality constraints

### ISSUE THREAD

**Issue by akaptano** [dynamicslab/pysindy#54]
Hello again! Before discovering this wonderful repo, I was using Loiseau's hard-thresholded least-squares algorithm which allows for linear equality constraints. I am wondering if you have any suggestions about a good way to incorporate this into pysindy, and I can go ahead and implement that. I am having a bit of trouble currently with the sklearn syntax, and the syntax of the base optimizer class doesn't look like it supports constraint matrices, so I wanted to ask y'all if there is a nice solution here before I resort to bulldozing all the nice code y'all wrote. 

Best,
Alan

**Comment by kpchamp** [comment]
I've actually implemented linear equality constraints into the SR3 optimizer (with the help of Peng & Sasha). I have it implemented in a local branch because it's part of a larger group of extensions we're working on for a paper using SR3, and we'll plan on adding that to the codebase once we've submitted the paper (hopefully within the next couple weeks).

We haven't looked into implementing the linear equality constraints in the thresholded least squares algorithm, but definitely had that in mind as an extension that should be implemented at some point. If you're game to take a crack at it, that would be awesome! My recommendation would be to either (1) create a new optimizer class (called something like ConstrainedSTLSQ) that takes constraint matrices as parameters, or (2) modify the current STLSQ class to take constraint matrices as optional parameters and does the constrained optimization if constraints are passed in. Brian or Markus may have other suggestions/opinions.

**Comment by briandesilva** [comment]
I agree with Kathleen's suggestions. If the implementation isn't too different from vanilla STLSQ, it's probably easiest to tack it onto that class. Otherwise you can create a new class that inherits from `STLSQ`.

**Comment by akaptano** [comment]
I'm not particularly fixed on using thresholded least squares, so I'm happy to use the constrained SR3 method if you don't mind sending that routine my way a little earlier (my impression is the performance should be fairly similar?). Having this would also help make sure my implementation of the linear equality constraints in thresholded least squares is consistent in structure. If not, no worries and I'll take a crack at the equality constraints for STLSQ sometime this week.

**Comment by briandesilva** [comment]
Implemented in #78.
