### ISSUE TITLE
Support for Time-Delayed system ?

### ISSUE THREAD

**Issue by Capri2014** [dynamicslab/pysindy#70]
Thanks for the lib and the introduction paper! One thing I am curious is that does the system supports system ID for time-delayed system?

**Comment by briandesilva** [comment]
At the moment we don't offer support for time-delayed systems. However, it should become possible to experiment with simple time-delay coordinates once I finish implementing SINDy with control (SINDYc). Basically what SINDYc does is draw a distinction between target variables--those for which you want to discover a differential equation--and control inputs, those which you want to include in your library, but shouldn't be present on the left-hand side of the sparse regression problem. I.e. instead of solving `X' = Theta(X) * Xi` you solve `X' = Theta(X, U) * Xi`. If you wanted you could pass in some time-delayed measurements as `U` instead of control inputs.

I'm planning to release a SINDYc implementation in the next day or two.

**Comment by briandesilva** [comment]
SINDYc was just added in #71, so it should now be possible to work with time-delays, albeit in a roundabout way.

**Comment by Capri2014** [comment]
Thanks!
