### ISSUE TITLE
ContextualVersionConflict: (scikit-learn 0.22.2.post1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scikit-learn[alldeps]>=0.23'), {'pysindy'})[BUG]

### ISSUE THREAD

**Issue by debottam123** [dynamicslab/pysindy#83]
### Reproducing code example:

import pysindy as ps
error:-
ContextualVersionConflict: (scikit-learn 0.22.2.post1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('scikit-learn[alldeps]>=0.23'), {'pysindy'})
```python
import pysindy
<< your code here >>
```

**Comment by briandesilva** [comment]
My guess is that this is due to the recent update to the requirements file to require scikit-learn version 0.23 or greater. Does updating to scikit-learn version 0.23 fix the problem?

**Comment by debottam123** [comment]
Restarting the runtime fixes this issue, though I am not sure about the causes of it.

**Comment by ConstantinosM** [comment]
I faced the same issue as well. Restarting runtime in colab fixed it. I am not sure what causes it. I tried to install sklearn with [alldeps] and pysindy was giving me the same error.

**Comment by briandesilva** [comment]
Just curious, which issue of sklearn do you have installed?

**Comment by ConstantinosM** [comment]
Colab comes with sklearn 0.22.2.post1 pre-installed. If I install pysindy (`pip install pysindy`) then it gives me a warning that sklearn requires alldeps. Then when I import pysindy and try to use it I get the same error as above (which is fixed if runtime is restarted). I installed other versions of sklearn (from 0.22 up to the latest one with/without [alldeps] argument) but stil I got this error. Only pysindy==0.15 did not have any issue at all and no warnings when installing it.

**Comment by briandesilva** [comment]
The alldeps warning comes from the following line in the requirements file: `scikit-learn[alldeps]>=0.23`. The alldeps option is supported for Scikit-learn version 0.23, but not 0.24. It simply ensures that all of sklearn's dependencies are installed along with it. I think you can safely ignore this warning.

I still suspect the `ContextualVersionConflict` is caused by the fact that the system has sklearn version 0.22 installed, while newer versions of PySINDy require version 0.23. Installing PySINDy version 0.15 probably worked because it required an earlier version of sklearn.
