### ISSUE TITLE
how to introduce control inputs for the system identificaiton?

### ISSUE THREAD

**Issue by tidecoder** [dynamicslab/pysindy#88]
Thanks for the excellent package for system identification. 
It seems it is working perfectly for cases:
Y = A*X + B  
where Y is a matrix of interested outputs, X is a matrix of state variables, B is a matrix of constant bias. 
####################################################################################
However, In many cases, there are control variables involved in such a relationship:
Y = A * X + B * U + C
Where Y is a matrix of interested outputs, X is a matrix of state variables, U is a matrix of control inputs, C is a matrix of constant bias.  
How do we do system identification problem with control inputs? 
Thanks.

**Comment by briandesilva** [comment]
The quick answer is that you pass in the control inputs when calling the `fit` function:
```python
model = ps.SINDy()
model.fit(x_train, u=u_train)
```

Check out the SINDYc section of this [example notebook](https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview.html#sindy-with-control-sindyc) for some examples.

**Comment by tidecoder** [comment]
Thanks. That make sense! 
It seems the control inputs in the example is a function of time. 
What if my control inputs are a vector? How do i handle it?

**Comment by briandesilva** [comment]
The control inputs passed to the `fit` method should be a vector if 1D or an array with each input given as a column vector otherwise. The only method that requires a function for the control input it `simulate`. We show what to do if you don't have a control function [here](https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview.html#simulate-forward-in-time-control-input-function-known). Essentially, you fit a linear interpolator to the control data you do have.

Which method is giving you trouble? Could you include a short sample of the code you're using and the error message that's generated?

**Comment by tidecoder** [comment]
thanks. Is simulate() equivalent to odeint()?  I have 200000 data points (vector length). It took 30 minutes and has not finished simulate(). Usually odeint() takes about 10 minutes to finish.

**Comment by briandesilva** [comment]
By default `simulate` uses `odeint` to do numerical integration. It might take longer than you're used to if the number of features in your SINDy model is large - either from selecting a large feature library or because your data is high-dimensional. I can look into ways to make `simulate` more efficient, but it might be a while before the fix is out.

**Comment by briandesilva** [comment]
After digging into it a bit more, it would take a considerable effort for us to speed up the `simulate` method. `simulate` is provided as a convenience function, so that one can quickly perform sanity checks on models learned with SINDy. It's somewhat outside the scope of this package to do fast, efficient numerical solution of ODEs.

With that being said, I'm adding it to our list of extensions and improvements that we'd like to implement. There are some higher priority tasks for the package though, so it might be a while before any progress is made on this front.
