### ISSUE TITLE
Control vector U with unkown function[BUG]

### ISSUE THREAD

**Issue by moujrid** [dynamicslab/pysindy#95]
Hello,

I have a question if you could please help me. I tried to use the pysindy with control on my own dataset. However, I have only the U time serie without any function. Model.fit works but when i try to simulate it throws an error that an x_new is above the interpolation range? Have you encountered this error before and de you any idea how to solve it ?

Thanks in advance for your feedback

**Comment by briandesilva** [comment]
See [this section](https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview.html#simulate-forward-in-time-unknown-control-input-function) of the documentation. The following factors contribute to the issue:
1. The default numerical integrator used by `SINDy.simulate` is `scipy.integrate.odeint`, an adaptive time-stepping routine. Since `odeint` is adaptive, it needs to be able to evaluate functions at various points in time, meaning control inputs need to be given as a callable function.
2. Sometimes you don't have a function for u, but you do have a time series. In that case, SINDy will form a spline interpolation of the time series and use that instead. However, since it's an interpolating function, if you try to evaluate it at a time outside of the original time series, it will complain.

The issue is either that you're trying to simulate for times when the control inputs aren't known or that the numerical integrator, `odeint`, is attempting to evaluate the interpolating function for u outside the domain where it's defined. You could either decrease the span of time over which you simulate or use a different integrator ([scipy.integrate](https://docs.scipy.org/doc/scipy/reference/integrate.html) has some other options). If you decide to do the latter, you will probably need to adjust the call signature of the integrator to match that which `SINDy.simulate` expects: `integrator(rhs, x0, t, **kwargs)`.

**Comment by msis** [comment]
This is what I used to get too, see #94 .
I think it's related to the `t` you are passing, not the `u`.

**Comment by briandesilva** [comment]
> This is what I used to get too, see #94 .
I think it's related to the t you are passing, not the u.

That could also be the problem. I will create a new release including the fix this afternoon.

**Comment by moujrid** [comment]
thank you for all you replies.

I tried to shift the time to start at 0 and also tried different time spans smaller than the actual time span of my time serie but the error keeps showing up

**Comment by briandesilva** [comment]
@moujrid, I just created a new release with the bug fix I alluded to earlier. See if you still encounter the error after updating to the latest version.
